alias: Random automation
description: >-
  Checks every 5 minutes if the specified automations are disabled between 10 PM and 5 AM and enables them
trigger:
  - platform: time_pattern
    minutes: /5
condition:
  - condition: time
    after: "22:00:00"
    before: "05:00:00"
  - condition: state
    entity_id: automation.studio_light  # studio_random = name of the automation
    state: "off"
action:
  - service: automation.turn_on
    target:
      entity_id: automation.studio_light
    data: {}
